export enum ErrorCode {
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  ACCOUNT_INACTIVE = 'ACCOUNT_INACTIVE',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  EMAIL_NOT_VERIFIED = 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Session
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_LIMIT_EXCEEDED = 'SESSION_LIMIT_EXCEEDED',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',
  INVALID_SESSION_TRANSITION = 'INVALID_SESSION_TRANSITION',
  SESSION_INCOMPLETE = 'SESSION_INCOMPLETE',

  // Question & Prep
  QUESTION_BANK_EMPTY = 'QUESTION_BANK_EMPTY',
  RUBRIC_NOT_FOUND = 'RUBRIC_NOT_FOUND',

  // Answer / Turn
  ANSWER_NOT_FOUND = 'ANSWER_NOT_FOUND',
  AUDIO_TOO_LARGE = 'AUDIO_TOO_LARGE',
  INVALID_AUDIO_URL = 'INVALID_AUDIO_URL',
  AUDIO_DOWNLOAD_FAILED = 'AUDIO_DOWNLOAD_FAILED',
  INVALID_ANSWER_TYPE = 'INVALID_ANSWER_TYPE',

  // Report
  REPORT_NOT_READY = 'REPORT_NOT_READY',

  // AI
  AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
  AI_RATE_LIMIT = 'AI_RATE_LIMIT',
  AI_QUOTA_EXCEEDED = 'AI_QUOTA_EXCEEDED',
  AI_TIMEOUT = 'AI_TIMEOUT',
  AI_EMPTY_RESPONSE = 'AI_EMPTY_RESPONSE',
  AI_INVALID_JSON = 'AI_INVALID_JSON',
  SCHEMA_VALIDATION_ERROR = 'SCHEMA_VALIDATION_ERROR',
  INVALID_SESSION_TYPE = 'INVALID_SESSION_TYPE',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE = 'MAINTENANCE_MODE',
}
