import type { PrismaClient } from '@prisma/client';

const QUESTIONS = [
  // ── Pair A: hr × VN (15 câu) ────────────────────────────────────────────
  { content: 'Hãy giới thiệu về bản thân bạn trong 2 phút.', sessionType: 'hr', difficulty: 1, contextPackId: 'VN', subcategory: 'self-introduction', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Tại sao bạn lựa chọn nghề IT/lập trình?', sessionType: 'hr', difficulty: 1, contextPackId: 'VN', subcategory: 'motivation', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Bạn biết gì về công ty và vị trí bạn đang ứng tuyển?', sessionType: 'hr', difficulty: 2, contextPackId: 'VN', subcategory: 'culture-fit', competencyDomain: 'D5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Bạn thích làm việc độc lập hay theo nhóm? Tại sao?', sessionType: 'hr', difficulty: 2, contextPackId: 'VN', subcategory: 'teamwork-preference', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Môi trường làm việc lý tưởng của bạn trông như thế nào?', sessionType: 'hr', difficulty: 2, contextPackId: 'VN', subcategory: 'culture-fit', competencyDomain: 'D5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Mô tả cách bạn giải thích một khái niệm kỹ thuật phức tạp cho người không có nền tảng IT.', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'communication', competencyDomain: 'D1', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Kể về một lần bạn thuyết phục thành công đồng nghiệp hoặc sếp chấp nhận ý kiến của bạn.', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'persuasion', competencyDomain: 'D1', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Kể về một lần bạn conflict với teammate. Bạn đã xử lý thế nào và kết quả ra sao?', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'conflict-resolution', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Điều gì thúc đẩy bạn làm việc hiệu quả nhất? Cho ví dụ cụ thể.', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'motivation', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Điểm yếu lớn nhất của bạn là gì và bạn đang cải thiện nó như thế nào?', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'self-awareness', competencyDomain: 'D6', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Kể về một kỹ năng bạn tự học trong 6 tháng gần nhất. Kết quả bạn đạt được là gì?', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'growth-mindset', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Kể về một vấn đề khó mà bạn đã giải quyết thành công. Quy trình tiếp cận của bạn là gì?', sessionType: 'hr', difficulty: 3, contextPackId: 'VN', subcategory: 'problem-solving', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Nếu deadline project bị rút ngắn đột ngột còn một nửa nhưng scope không đổi, bạn sẽ làm gì?', sessionType: 'hr', difficulty: 4, contextPackId: 'VN', subcategory: 'prioritization', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Nếu sếp giao task theo hướng tiếp cận mà bạn cho là không tối ưu, bạn xử lý thế nào?', sessionType: 'hr', difficulty: 4, contextPackId: 'VN', subcategory: 'upward-communication', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Nhìn lại 1 năm qua, thành tích bạn tự hào nhất là gì và điều gì bạn muốn làm khác đi?', sessionType: 'hr', difficulty: 5, contextPackId: 'VN', subcategory: 'reflection', competencyDomain: 'D6', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  // ── Pair B: hr × Western (15 câu) ───────────────────────────────────────
  { content: 'Tell me about yourself.', sessionType: 'hr', difficulty: 1, contextPackId: 'Western', subcategory: 'self-introduction', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Why did you choose a career in software engineering?', sessionType: 'hr', difficulty: 1, contextPackId: 'Western', subcategory: 'motivation', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'What do you know about our company and why do you want to work here?', sessionType: 'hr', difficulty: 2, contextPackId: 'Western', subcategory: 'culture-fit', competencyDomain: 'D5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Do you prefer working independently or on a team? Give an example.', sessionType: 'hr', difficulty: 2, contextPackId: 'Western', subcategory: 'teamwork-preference', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Describe your ideal work environment.', sessionType: 'hr', difficulty: 2, contextPackId: 'Western', subcategory: 'culture-fit', competencyDomain: 'D5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Describe a time you had to explain a complex technical concept to a non-technical stakeholder.', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'communication', competencyDomain: 'D1', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Tell me about a time you successfully persuaded a colleague or manager to adopt your approach.', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'persuasion', competencyDomain: 'D1', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Tell me about a time you had a conflict with a coworker. How did you handle it and what was the outcome?', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'conflict-resolution', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'What motivates you to do your best work? Give a concrete example.', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'motivation', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'What is your biggest weakness, and what are you actively doing to improve it?', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'self-awareness', competencyDomain: 'D6', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Tell me about a skill you taught yourself in the past six months. What was the outcome?', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'growth-mindset', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Describe a difficult problem you solved successfully. Walk me through your approach.', sessionType: 'hr', difficulty: 3, contextPackId: 'Western', subcategory: 'problem-solving', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'If a project deadline was suddenly cut in half with no scope reduction, what would you do?', sessionType: 'hr', difficulty: 4, contextPackId: 'Western', subcategory: 'prioritization', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'If your manager assigns a task using an approach you believe is suboptimal, how do you handle it?', sessionType: 'hr', difficulty: 4, contextPackId: 'Western', subcategory: 'upward-communication', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Looking back at the past year, what is your greatest accomplishment and what would you do differently?', sessionType: 'hr', difficulty: 5, contextPackId: 'Western', subcategory: 'reflection', competencyDomain: 'D6', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  // ── Pair C: technical × VN (15 câu) ─────────────────────────────────────
  { content: 'REST là gì và tại sao nó phổ biến? Nêu ít nhất 3 đặc điểm chính.', sessionType: 'technical', difficulty: 1, contextPackId: 'VN', subcategory: 'web-fundamentals', competencyDomain: 'TD1', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Sự khác biệt giữa SQL và NoSQL là gì? Khi nào bạn chọn cái nào?', sessionType: 'technical', difficulty: 2, contextPackId: 'VN', subcategory: 'databases', competencyDomain: 'TD1', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Git workflow bạn hay dùng trong dự án nhóm là gì? Giải thích các bước từ feature đến merge.', sessionType: 'technical', difficulty: 2, contextPackId: 'VN', subcategory: 'version-control', competencyDomain: 'TD2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Khi nào bạn dùng async/await thay vì Promise chain? Cho ví dụ cụ thể.', sessionType: 'technical', difficulty: 2, contextPackId: 'VN', subcategory: 'async-programming', competencyDomain: 'TD1', applicableRoles: ['backend', 'frontend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Khi code của bạn không chạy như mong đợi, quy trình debug của bạn là gì?', sessionType: 'technical', difficulty: 2, contextPackId: 'VN', subcategory: 'debugging', competencyDomain: 'TD5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'SOLID principles là gì? Giải thích Single Responsibility với ví dụ thực tế.', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'design-principles', competencyDomain: 'TD4', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Bạn xử lý N+1 query problem trong ORM như thế nào? Cho ví dụ code cụ thể.', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'database-optimization', competencyDomain: 'TD2', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Mô tả cách bạn thiết kế REST API endpoint cho một feature CRUD đơn giản. Nêu rõ HTTP methods và response shapes.', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'api-design', competencyDomain: 'TD2', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Code review là gì và bạn chú ý điều gì nhất khi review code của người khác?', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'code-quality', competencyDomain: 'TD4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Unit test và integration test khác nhau như thế nào? Bạn viết test như thế nào trong project?', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'testing', competencyDomain: 'TD4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Bạn dùng tool/technique gì để detect performance bottleneck trong application?', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'performance', competencyDomain: 'TD5', applicableRoles: ['backend', 'frontend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'Nếu hệ thống cần scale từ 1.000 lên 100.000 concurrent users, bạn sẽ thay đổi architecture như thế nào?', sessionType: 'technical', difficulty: 3, contextPackId: 'VN', subcategory: 'scalability', competencyDomain: 'TD3', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'Làm thế nào để đảm bảo security cho một REST API endpoint nhận user input? Liệt kê ít nhất 5 biện pháp.', sessionType: 'technical', difficulty: 4, contextPackId: 'VN', subcategory: 'security', competencyDomain: 'TD4', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'Kể về một production bug khó nhất bạn từng gặp. Bạn reproduce, diagnose và fix nó như thế nào?', sessionType: 'technical', difficulty: 4, contextPackId: 'VN', subcategory: 'debugging', competencyDomain: 'TD5', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Thiết kế sơ bộ một hệ thống URL shortener (như bit.ly). Nêu các thành phần chính, data model, và cách handle collision.', sessionType: 'technical', difficulty: 5, contextPackId: 'VN', subcategory: 'system-design', competencyDomain: 'TD3', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  // ── Pair D: technical × Western (15 câu) ────────────────────────────────
  { content: 'What is REST and why is it widely used? Name at least 3 key characteristics.', sessionType: 'technical', difficulty: 1, contextPackId: 'Western', subcategory: 'web-fundamentals', competencyDomain: 'TD1', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'What are the differences between SQL and NoSQL databases? When would you choose one over the other?', sessionType: 'technical', difficulty: 2, contextPackId: 'Western', subcategory: 'databases', competencyDomain: 'TD1', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Describe the Git workflow your team uses. Walk through the steps from creating a feature to merging it.', sessionType: 'technical', difficulty: 2, contextPackId: 'Western', subcategory: 'version-control', competencyDomain: 'TD2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'When would you use async/await versus Promise chaining? Give a concrete example.', sessionType: 'technical', difficulty: 2, contextPackId: 'Western', subcategory: 'async-programming', competencyDomain: 'TD1', applicableRoles: ['backend', 'frontend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Walk me through your debugging process when code is not behaving as expected.', sessionType: 'technical', difficulty: 2, contextPackId: 'Western', subcategory: 'debugging', competencyDomain: 'TD5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'What are the SOLID principles? Explain Single Responsibility with a real-world example.', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'design-principles', competencyDomain: 'TD4', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'How do you handle the N+1 query problem in an ORM? Show a code example.', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'database-optimization', competencyDomain: 'TD2', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Describe how you would design REST API endpoints for a simple CRUD feature. Specify HTTP methods and response shapes.', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'api-design', competencyDomain: 'TD2', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'What do you focus on during a code review? What makes code "reviewable"?', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'code-quality', competencyDomain: 'TD4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'How do unit tests differ from integration tests? How do you approach testing in your projects?', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'testing', competencyDomain: 'TD4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'What tools or techniques do you use to identify performance bottlenecks in an application?', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'performance', competencyDomain: 'TD5', applicableRoles: ['backend', 'frontend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'If your system needs to scale from 1,000 to 100,000 concurrent users, what architectural changes would you make?', sessionType: 'technical', difficulty: 3, contextPackId: 'Western', subcategory: 'scalability', competencyDomain: 'TD3', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'How would you secure a REST API endpoint that accepts user input? List at least 5 measures.', sessionType: 'technical', difficulty: 4, contextPackId: 'Western', subcategory: 'security', competencyDomain: 'TD4', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'Describe the hardest production bug you have ever encountered. How did you reproduce, diagnose, and fix it?', sessionType: 'technical', difficulty: 4, contextPackId: 'Western', subcategory: 'debugging', competencyDomain: 'TD5', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Design a simplified URL shortener system (like bit.ly). Describe the main components, data model, and how you handle hash collisions.', sessionType: 'technical', difficulty: 5, contextPackId: 'Western', subcategory: 'system-design', competencyDomain: 'TD3', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  // ── Pair E: mixed × VN (15 câu) ─────────────────────────────────────────
  { content: 'Hãy giới thiệu bản thân và một project kỹ thuật bạn tự hào nhất.', sessionType: 'mixed', difficulty: 1, contextPackId: 'VN', subcategory: 'self-introduction', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Bạn biết gì về Git? Mô tả quy trình từ code đến push lên remote.', sessionType: 'mixed', difficulty: 2, contextPackId: 'VN', subcategory: 'version-control', competencyDomain: 'TD1', applicableRoles: ['all'], applicableLevels: ['junior'] },
  { content: 'Gặp vấn đề không biết giải quyết trong code, bạn làm gì?', sessionType: 'mixed', difficulty: 2, contextPackId: 'VN', subcategory: 'problem-solving', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Bạn nghĩ gì về việc làm thêm giờ khi project cần?', sessionType: 'mixed', difficulty: 2, contextPackId: 'VN', subcategory: 'culture-fit', competencyDomain: 'D5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Bạn tự đánh giá kỹ năng giao tiếp của mình thế nào? Cho ví dụ cụ thể.', sessionType: 'mixed', difficulty: 2, contextPackId: 'VN', subcategory: 'communication', competencyDomain: 'D1', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Điều gì khiến bạn muốn theo đuổi sự nghiệp trong ngành IT và vì sao lại chọn vai trò này?', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'motivation', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Bạn đã xây dựng project nào ấn tượng nhất? Mô tả các quyết định kỹ thuật quan trọng.', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'technical-experience', competencyDomain: 'TD2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Kể về một lần bạn phải học công nghệ mới trong thời gian ngắn. Cách tiếp cận và kết quả?', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'learning-agility', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Bạn hiểu CI/CD là gì? Tại sao nó quan trọng và bạn đã dùng nó chưa?', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'devops-awareness', competencyDomain: 'TD3', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'Bạn làm gì để giữ code sạch và dễ bảo trì khi làm việc theo nhóm?', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'code-quality', competencyDomain: 'TD4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Mô tả trải nghiệm làm việc nhóm kỹ thuật của bạn. Bạn thường đóng vai trò gì?', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'teamwork', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'So với yêu cầu của vị trí này, bạn thấy mình đang thiếu kỹ năng gì? Kế hoạch bù đắp của bạn là gì?', sessionType: 'mixed', difficulty: 3, contextPackId: 'VN', subcategory: 'self-awareness', competencyDomain: 'D6', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Nếu phát hiện đồng nghiệp mắc lỗi nghiêm trọng gần deadline release, bạn xử lý thế nào?', sessionType: 'mixed', difficulty: 4, contextPackId: 'VN', subcategory: 'integrity', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Design một REST API đơn giản cho hệ thống quản lý task. Nêu endpoints chính, HTTP methods, và data model.', sessionType: 'mixed', difficulty: 4, contextPackId: 'VN', subcategory: 'api-design', competencyDomain: 'TD2', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'Kể về một project nhóm thất bại hoặc gặp khó khăn lớn. Bạn đóng góp gì, lỗi ở đâu, bài học bạn rút ra?', sessionType: 'mixed', difficulty: 5, contextPackId: 'VN', subcategory: 'reflection', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  // ── Pair F: mixed × Western (15 câu) ────────────────────────────────────
  { content: 'Introduce yourself and walk me through your most impressive technical project.', sessionType: 'mixed', difficulty: 1, contextPackId: 'Western', subcategory: 'self-introduction', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Tell me about your experience with Git. Describe your workflow from coding to pushing to remote.', sessionType: 'mixed', difficulty: 2, contextPackId: 'Western', subcategory: 'version-control', competencyDomain: 'TD1', applicableRoles: ['all'], applicableLevels: ['junior'] },
  { content: 'When you hit a blocker on a coding problem you cannot solve, what do you do?', sessionType: 'mixed', difficulty: 2, contextPackId: 'Western', subcategory: 'problem-solving', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'How do you feel about working overtime when a project demands it?', sessionType: 'mixed', difficulty: 2, contextPackId: 'Western', subcategory: 'culture-fit', competencyDomain: 'D5', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'How would you rate your communication skills and why? Give a specific example.', sessionType: 'mixed', difficulty: 2, contextPackId: 'Western', subcategory: 'communication', competencyDomain: 'D1', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'What drew you to a career in software engineering, and why this specific role?', sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'motivation', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: "What's the most impressive project you've built? Describe the key technical decisions you made.", sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'technical-experience', competencyDomain: 'TD2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'Tell me about a time you had to learn a new technology quickly. How did you approach it and what was the result?', sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'learning-agility', competencyDomain: 'D2', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'What do you know about CI/CD? Why is it important and have you used it in your projects?', sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'devops-awareness', competencyDomain: 'TD3', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['junior', 'mid'] },
  { content: 'What do you do to keep code clean and maintainable when working on a team?', sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'code-quality', competencyDomain: 'TD4', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Describe your experience working in technical teams. What role do you typically play?', sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'teamwork', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['junior', 'mid', 'senior'] },
  { content: 'Compared to the requirements of this role, what skills do you think you are lacking? What is your plan to address the gaps?', sessionType: 'mixed', difficulty: 3, contextPackId: 'Western', subcategory: 'self-awareness', competencyDomain: 'D6', applicableRoles: ['all'], applicableLevels: ['junior', 'mid'] },
  { content: 'If you discovered a teammate made a serious mistake close to a release deadline, how would you handle it?', sessionType: 'mixed', difficulty: 4, contextPackId: 'Western', subcategory: 'integrity', competencyDomain: 'D4', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
  { content: 'Design a simple REST API for a task management system. Describe the main endpoints, HTTP methods, and data model.', sessionType: 'mixed', difficulty: 4, contextPackId: 'Western', subcategory: 'api-design', competencyDomain: 'TD2', applicableRoles: ['backend', 'fullstack'], applicableLevels: ['mid', 'senior'] },
  { content: 'Tell me about a team project that failed or faced major challenges. What was your contribution, where did things go wrong, and what did you learn?', sessionType: 'mixed', difficulty: 5, contextPackId: 'Western', subcategory: 'reflection', competencyDomain: 'D3', applicableRoles: ['all'], applicableLevels: ['mid', 'senior'] },
];

export async function seedQuestionBank(prisma: PrismaClient): Promise<void> {
  const count = await prisma.questionBank.count();
  if (count >= 90) {
    console.log('question_bank: already seeded, skipping');
    return;
  }

  await prisma.questionBank.createMany({
    data: QUESTIONS,
    skipDuplicates: true,
  });

  console.log(`question_bank: seeded ${QUESTIONS.length} questions`);
}
