export enum ErrorCode {
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // Session
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_LIMIT_EXCEEDED = 'SESSION_LIMIT_EXCEEDED',
  SESSION_NOT_ACTIVE = 'SESSION_NOT_ACTIVE',

  // Answer / Turn
  ANSWER_NOT_FOUND = 'ANSWER_NOT_FOUND',
  AUDIO_TOO_LARGE = 'AUDIO_TOO_LARGE',
  INVALID_ANSWER_TYPE = 'INVALID_ANSWER_TYPE',

  // Report
  REPORT_NOT_READY = 'REPORT_NOT_READY',

  // AI
  AI_SERVICE_ERROR = 'AI_SERVICE_ERROR',
  SCHEMA_VALIDATION_ERROR = 'SCHEMA_VALIDATION_ERROR',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}
