export const PERSONALITY_OPTIONS = [
  { value: '', label: 'Chọn tính cách' },
  { value: 'introvert', label: 'Hướng nội (Introvert)' },
  { value: 'extrovert', label: 'Hướng ngoại (Extrovert)' },
  { value: 'ambivert', label: 'Vừa hướng nội vừa hướng ngoại (Ambivert)' },
  { value: 'analytical', label: 'Phân tích (Analytical)' },
  { value: 'creative', label: 'Sáng tạo (Creative)' },
  { value: 'leader', label: 'Lãnh đạo (Leader)' },
  { value: 'teamplayer', label: 'Làm việc nhóm tốt (Team Player)' },
]

export const TARGET_POSITION_OPTIONS = [
  { value: '', label: 'Chọn vị trí mục tiêu' },
  { value: 'frontend', label: 'Frontend Developer' },
  { value: 'backend', label: 'Backend Developer' },
  { value: 'fullstack', label: 'Fullstack Developer' },
  { value: 'mobile', label: 'Mobile Developer' },
  { value: 'devops', label: 'DevOps Engineer' },
  { value: 'sre', label: 'Site Reliability Engineer' },
  { value: 'cloud', label: 'Cloud Engineer' },
  { value: 'security', label: 'Security Engineer' },
  { value: 'data', label: 'Data Engineer / Analyst' },
  { value: 'data_scientist', label: 'Data Scientist' },
  { value: 'ml', label: 'Machine Learning Engineer' },
  { value: 'ai', label: 'AI Engineer' },
  { value: 'mlops', label: 'MLOps Engineer' },
  { value: 'dba', label: 'Database Administrator' },
  { value: 'sysadmin', label: 'System Administrator' },
  { value: 'qa', label: 'QA Engineer' },
  { value: 'game', label: 'Game Developer' },
  { value: 'embedded', label: 'Embedded Engineer' },
  { value: 'pm', label: 'Product Manager' },
  { value: 'project_manager', label: 'Project Manager' },
  { value: 'scrum_master', label: 'Scrum Master' },
  { value: 'solution_architect', label: 'Solution Architect' },
  { value: 'erp_crm', label: 'ERP/CRM Consultant' },
  { value: 'technical_writer', label: 'Technical Writer' },
  { value: 'designer', label: 'UI/UX Designer' },
  { value: 'other', label: 'Khác' },
]

export const EXPERIENCE_LEVEL_OPTIONS = [
  { value: '', label: 'Chọn mức kinh nghiệm' },
  { value: 'intern', label: 'Intern / Thực tập sinh' },
  { value: 'fresher', label: 'Fresher (0–6 tháng)' },
  { value: 'junior', label: 'Junior (6–12 tháng)' },
  { value: 'mid', label: 'Mid-level (1–3 năm)' },
  { value: 'senior', label: 'Senior (3+ năm)' },
]

export const EDUCATION_DEGREE_OPTIONS = [
  { value: '', label: 'Chọn trình độ' },
  { value: 'high_school', label: 'THPT' },
  { value: 'college', label: 'Cao đẳng' },
  { value: 'bachelor', label: 'Đại học (Cử nhân)' },
  { value: 'engineer', label: 'Đại học (Kỹ sư)' },
  { value: 'master', label: 'Thạc sĩ' },
  { value: 'phd', label: 'Tiến sĩ' },
  { value: 'other', label: 'Khác' },
]

export const TECH_STACK_OPTIONS: Record<string, string[]> = {
  Frontend: [
    'React',
    'Next.js',
    'Vue.js',
    'Nuxt.js',
    'Angular',
    'Svelte',
    'Astro',
    'Remix',
    'TypeScript',
    'JavaScript',
    'HTML/CSS',
    'Tailwind CSS',
    'Bootstrap',
    'Material UI',
    'Shadcn/ui',
    'Redux',
    'TanStack Query',
    'Vite',
    'Webpack',
  ],
  Backend: [
    'Node.js',
    'Express',
    'NestJS',
    'Fastify',
    'Java',
    'Spring Boot',
    'C#',
    'ASP.NET Core',
    'Python',
    'Django',
    'FastAPI',
    'Flask',
    'Go',
    'Gin',
    'PHP',
    'Laravel',
    'Ruby on Rails',
    'Rust',
    'Axum',
    'GraphQL',
    'REST API',
    'gRPC',
    'Microservices',
  ],
  Mobile: [
    'React Native',
    'Flutter',
    'Swift',
    'SwiftUI',
    'Objective-C',
    'Kotlin',
    'Java Android',
    'Android SDK',
    'Jetpack Compose',
    'iOS SDK',
    'Xcode',
    'Android Studio',
    'Firebase',
    'Expo',
  ],
  'Data / AI': [
    'Python',
    'SQL',
    'R',
    'Pandas',
    'NumPy',
    'scikit-learn',
    'TensorFlow',
    'PyTorch',
    'Keras',
    'Spark',
    'Airflow',
    'dbt',
    'Kafka',
    'Snowflake',
    'BigQuery',
    'Databricks',
    'Power BI',
    'Tableau',
    'LangChain',
    'LangGraph',
    'RAG',
    'Vector Database',
    'OpenAI API',
    'Hugging Face',
  ],
  Database: [
    'PostgreSQL',
    'MySQL',
    'SQLite',
    'SQL Server',
    'Oracle',
    'MongoDB',
    'Redis',
    'Elasticsearch',
    'OpenSearch',
    'DynamoDB',
    'Cassandra',
    'Neo4j',
    'Supabase',
    'Firebase/Firestore',
    'ClickHouse',
    'InfluxDB',
  ],
  'Cloud / DevOps / SRE': [
    'Docker',
    'Kubernetes',
    'AWS',
    'Azure',
    'Google Cloud',
    'Cloudflare',
    'Terraform',
    'Ansible',
    'Helm',
    'Nginx',
    'Linux',
    'CI/CD',
    'GitHub Actions',
    'GitLab CI',
    'Jenkins',
    'Argo CD',
    'Prometheus',
    'Grafana',
    'Datadog',
    'New Relic',
    'ELK Stack',
  ],
  'QA / Testing': [
    'Manual Testing',
    'Automation Testing',
    'Selenium',
    'Playwright',
    'Cypress',
    'Jest',
    'Vitest',
    'JUnit',
    'Pytest',
    'Postman',
    'Swagger/OpenAPI',
    'JMeter',
    'k6',
    'Appium',
    'TestRail',
  ],
  Security: [
    'OWASP',
    'DevSecOps',
    'IAM',
    'OAuth2/OIDC',
    'SSO',
    'JWT',
    'SAST',
    'DAST',
    'SonarQube',
    'Burp Suite',
    'ZAP',
    'SIEM',
    'WAF',
    'Vulnerability Assessment',
    'Penetration Testing',
  ],
  'Game / 3D / XR': [
    'Unity',
    'Unreal Engine',
    'C#',
    'C++',
    'Godot',
    'GDScript',
    'OpenGL',
    'WebGL',
    'Three.js',
    'Blender',
    'ARKit',
    'ARCore',
    'visionOS',
  ],
  'Embedded / IoT / Systems': [
    'C',
    'C++',
    'Rust',
    'Embedded Linux',
    'RTOS',
    'FreeRTOS',
    'ARM',
    'STM32',
    'Arduino',
    'Raspberry Pi',
    'ESP32',
    'MQTT',
    'CAN Bus',
    'MicroPython',
  ],
  'Enterprise / ERP / Low-code': [
    'SAP',
    'Salesforce',
    'ServiceNow',
    'Odoo',
    'Microsoft Dynamics',
    'Power Platform',
    'SharePoint',
    'WordPress',
    'Drupal',
  ],
  'Tools / Collaboration': [
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'Jira',
    'Confluence',
    'Notion',
    'Slack',
    'Figma',
    'Miro',
    'Markdown',
  ],
}

export const TECH_CATEGORIES = [
  { key: 'language' as const, label: 'Ngôn ngữ lập trình' },
  { key: 'framework' as const, label: 'Framework / Library' },
  { key: 'os' as const, label: 'Hệ điều hành' },
  { key: 'database' as const, label: 'Cơ sở dữ liệu' },
  { key: 'platform' as const, label: 'Platform / Cloud' },
  { key: 'devtool' as const, label: 'Dev Management Tools' },
] as const

export type TechCategory = (typeof TECH_CATEGORIES)[number]['key']

export const TECH_OPTIONS: Record<TechCategory, string[]> = {
  language: ['JavaScript', 'TypeScript', 'Python', 'Java', 'Go', 'Rust', 'C', 'C++', 'C#', 'PHP', 'Ruby', 'Swift', 'Kotlin', 'Dart', 'SQL', 'R', 'GDScript'],
  framework: ['React', 'Next.js', 'Vue.js', 'Nuxt.js', 'Angular', 'Svelte', 'Astro', 'Remix', 'NestJS', 'Express', 'Fastify', 'Django', 'FastAPI', 'Flask', 'Spring Boot', 'ASP.NET Core', 'Laravel', 'Ruby on Rails', 'Flutter', 'React Native', 'SwiftUI', 'Jetpack Compose', 'Unity', 'Unreal Engine'],
  os: ['Linux', 'Ubuntu', 'Debian', 'CentOS', 'macOS', 'Windows', 'Embedded Linux', 'RTOS', 'FreeRTOS'],
  database: ['PostgreSQL', 'MySQL', 'MongoDB', 'Redis', 'SQLite', 'SQL Server', 'Oracle', 'Supabase', 'Firebase/Firestore', 'DynamoDB', 'Elasticsearch', 'OpenSearch', 'Cassandra', 'Neo4j', 'ClickHouse', 'InfluxDB', 'Vector Database'],
  platform: ['AWS', 'Google Cloud', 'Azure', 'Cloudflare', 'Vercel', 'Netlify', 'Railway', 'Heroku', 'DigitalOcean', 'Docker', 'Kubernetes', 'Terraform', 'Ansible', 'Helm', 'Salesforce', 'SAP', 'ServiceNow', 'Power Platform'],
  devtool: ['Git', 'GitHub', 'GitLab', 'Bitbucket', 'Jira', 'Confluence', 'Notion', 'Slack', 'Jenkins', 'GitHub Actions', 'GitLab CI', 'CircleCI', 'Argo CD', 'Prometheus', 'Grafana', 'Datadog', 'New Relic', 'Postman', 'Swagger/OpenAPI', 'Playwright', 'Cypress', 'Selenium', 'Figma', 'Miro'],
}

export const LANGUAGE_FRAMEWORK_MAP: Record<string, string[]> = {
  JavaScript: ['React', 'Next.js', 'Vue.js', 'Nuxt.js', 'Angular', 'Express', 'Fastify', 'NestJS', 'Svelte'],
  TypeScript: ['React', 'Next.js', 'Vue.js', 'Nuxt.js', 'Angular', 'NestJS', 'Express', 'Fastify', 'Svelte'],
  Python: ['Django', 'FastAPI', 'Flask', 'Pandas', 'NumPy', 'scikit-learn', 'TensorFlow', 'PyTorch'],
  Java: ['Spring Boot'],
  'C#': ['ASP.NET Core', 'Unity'],
  PHP: ['Laravel'],
  Ruby: ['Ruby on Rails'],
  Dart: ['Flutter'],
  Kotlin: ['Jetpack Compose'],
  Swift: ['SwiftUI'],
  Rust: ['Axum'],
}
